name = "bgm-landing"
main = ".open-next/worker.js"
compatibility_date = "2025-12-24" # Use the current date
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_CACHE_METHODS"
id = "<your-kv-id>"