name = "bgm-landing"
main = ".open-next/worker.js"
compatibility_date = "2025-12-24" 
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "my-next-cache-bucket"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "bgm-landing"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"